# -*- coding: utf-8 -*-
"""GerakPeluru.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYZVt1kglFp-rYsCu9uM231MgWQ8Lj-b

# SIMULASI GERAK PELURU

Pada Program berikut akan dibuat contoh Source Code yang membandingkan antara solusi matematis dengan pendekatan Numerik beserta Eksak.

### MENGINPUTKAN SEMUA VARIABEL YANG DIBUTUHKAN
"""

import math

Vo     = 20 #dalam satuan m/s^2
theta  = math.radians(60)
Xo     = 0
Yo     = 0
T      = 5
N      = 100
g      = 10
X_Num  = []
Y_Num  = []
Vy_Num = []
X_Eks  = []
Y_Eks  = []

"""###INISIALISASI PARAMETER UNTUK SOLUSI NUMERIK DAN EKSAK"""

X_Num.append(Xo)
Y_Num.append(Yo)
X_Eks.append(Xo)
Y_Eks.append(Yo)

deltaT   = T/N
Vx       = Vo*math.cos(theta)
Vy_Num.append(Vo*math.sin(theta))

"""### MENGHITUNG SOLUSI NUMERIK DARI KASUS DIATAS"""

i = 0
while i <= N:
  X_Num.append(X_Num[i] + Vx * deltaT)
  Vy_Num.append(-g*deltaT + Vy_Num[i])
  Y_Num.append(Y_Num[i] + (g*deltaT**2)+(Vy_Num[i+1]*deltaT))
  i=i+1

"""###MENGHITUNG SOLUSI EKSAK DARI KASUS DIATAS"""

i = 0
while i <= N:
  X_Eks.append(Vo*math.cos(theta)*(i*deltaT))
  Y_Eks.append( (-(0.5)*g*(i*deltaT)**2) +(i*deltaT*Vo*math.sin(theta)))
  i=i+1

"""### MENAMPILKAN UNTUK SOLUSI EKSAK DAN SOLUSI NUMERIK"""

plt.plot(X_Eks, Y_Eks, '-b', label='Solusi Eksak')
plt.plot(X_Num, Y_Num, '-r', label='Solusi Numerik')
plt.legend(loc='upper right')
plt.title('Perbandingan Plot Solusi Eksak dan Solusi Numerik')
plt.xlabel('x(t)')
plt.ylabel('y(t)')
plt.show()